### ISSUE TITLE
Worried about the politically correct world police

### ISSUE THREAD

**Issue by bittner** [tim-one/tim-one.github.io#50]
Dear Tim,

I read [your reply](https://tim-one.github.io/psf/ban) on what happen(ed) on the Python forum. Let me just take the chance to say, personally to you, that I'm deeply sorry about what's happening in that community. This is not meant as a political outcry (you may want to delete this issue after reading to make sure nobody interprets it that way). I feel sorry because the Python language, alongside with the GNU/Linux operating system, has accompanied and formed an important part of my identity. I also feel sorry because I grew up with the certainty that people who make great accomplishments in a field are granted the respect that those accomplishments deserve. This building of my convictions has started to crumble and that worries me.

I'm European, and so I do communicate differently. Naturally, I also have different political views than likely the average person from North America (I have friends in Colorado, New York City and Texas)—if an "average person" exists. That said, I see the topic of moderating public discourse much on the rise, specifically since COVID and fueled by social media. Yes, "free speech" is a difficult topic, just as "fact checking" is one. And what is better, communism or capitalism?—You should be free to choose.

But rather than installing a "world police" that is entitled to decide on what is right and what is wrong, I'd defend the right of people having opinions different from mine to be allowed to express those—in the humble hope they also share this view. In the name of democracy, in the name of free speech. Freedom is difficult to have, we have to defend it and share the benefits of it. Of course, we need to do that peacefully. On a side note, what "peacefully" means might be different in different cultures. What might be perceived by one person as an "interactive discussion" and "learning new views from each other" might be seen by the other side as "offensive behavior" and "not accepting other people's point of view".

There should be no police being allowed to judge things like that. My vision of a society that I want to live in is one where people try to understand each other, even when this is difficult sometimes. I see the complaints of people in the forum, and I feel I know what they talk about. Now, when they criticize the police they get put in jail! Wow, what a great society. – I'd like to live in a society where it's allowed to discuss the behavior of the police, where you have a chance for justice when there is abuse of power. A society where this is not possible is something that reminds of what we all know from movies about (European) governments of the early last century. We don't want that. Nobody wants that, I'm sure.

Instead of "enforcement" of law (what a cruel word!) we should be motivating each other to be better individuals. We should make each other understand our expectations. Nobody should have the right to point to an established list of laws, just waiting for others to violate them, which would allow them to exercise prosecution. A society with laws of a dictator is still dictatorship, even worse when there is no mention of "benevolent".

**Comment by tim-one** [comment]
I'd say we're kindred spirits 😃 

My case seems even darker, though. My list of "offenses" is nearly total contrived bullshit. For example, [I pick apart one here](https://tim-one.github.io/psf/silly).
    
That is, they're not attacking me for what I said. They're just making stuff up, or even claiming I said the exact opposite of what I said.

I don't believe anyone outside the PSF echo chamber has gotten a straight answer to what this is _really_ about. I certainly haven't been given one.

So it's more like a "We're a top-down collective now; individuals don't matter; we can crush anyone, by any means necessary, and here's the proof".

I'll always love the Python language and the actual Python community. But the PSF is not the community, and the PSF no longer speaks for the community. The PSF speaks for the PSF now, on its own weird power trip.

I don't think it's a coincidence either that the PSF is a US corporation. Contrary to its public propagande, the US is remarkably prudish, violent, and intolerant. For example, the US has the highest incarceration rate in the world (excepting, perhaps, North Korea), and routinely bullies other countries (both militarily and economically).

But I'm long retired, and there's nothing they can do to me that really matters. No target of a "temporary" ban has ever come back, because nobody ever _wants_ to come back after this calculatedly cruel process. I suppose they thought I'd just slink away in silence too. Ha! They don't know me at all 😉

**Comment by bittner** [comment]
The stupid war in Free Software communities is not over yet. After the comeback of Donald Trump there's more fuel also [on the other side of the debate](https://lunduke.com/). Be it what it is, I've gained some sudden insight I'd like to share here. This is thanks to the beautiful GNOME desktop. Because, apart from Python, Rust and Nix, also the [GNOME project](https://www.gnome.org/) was affected by <q>CoC moderation</q>. I didn't know to what extend.

Tobias Bernard, an apparently Berlin-based GNOME UI designer, has recently published <q>[The Elephant in the Room](https://blogs.gnome.org/tbernard/2025/04/23/the-elephant-in-the-room/)</q> on his official GNOME blog _<q>Space and Meaning</q>_, breaking the silence about the removal of his fellow countryman [Sonny Piers](https://blog.sonny.re/retrospective-as-gnome-director), former director of the GNOME board ([video review](https://youtu.be/6YnrAZIrTbA)). After reading the reader comments it stroke me: What is this political, right-wing vs left-wing, wrangling actually about? – And I wrote this comment:

> _2024 was a terrible year for Free Software. For Rust. For Nix. For Python. For GNOME, and other communities. For Gartner, 2024 was a year of growing Open Source adoption. Maybe it's not a coincidence that those two things go together._
> 
> _FLOSS is certainly on a maturation path. For what 2024 was worth, it feels like the 4chan community spirit has swapped over to Free Software projects. The power is there now, Open Source controls the world. Anonymous has lost its attraction. That's where the politicisation comes from. It's not the attraction of democratic values._
> 
> _I hope we'll get over this soon. I'd love to get back to just programming and solving engineering problems. Not having to worry about abuse of power and pseudo-political debate. I love the beauty, the user-friendlyness of the GNOME desktop and its infrastructure. Don't spoil it._
> 
> _Love everyone who contributes to better software._

As an interested reader, you may also want to read a [follow-up answer](https://blogs.gnome.org/aday/2025/04/25/on-elephants/) from Allan Day, apparently a current GNOME board member, though not involved in the proceedings related to the removal of Sonny, he claims. Everything available nicely listed in chronological order on [Planet GNOME](https://planet.gnome.org/), as always.

## 4chan Anarchy

I read Parmy Olson's book <q>We Are Anonymous</q> last year, which came back as a memory now. Anonymous was really that, a bunch of boys (no girls) that were testing the limits of what they could do with the power they had in their hands. While just one or two of them were interested in standing up to the Secret Services, most of them were just living a careless life.
